---
all:
  hosts:
    db_server:
      ansible_host: "{{ lookup('env', 'HOST_B') | default('mac', true) }}"
      ansible_user: "{{ lookup('env', 'USER_B') | default('yog404', true) }}"
      ansible_become: yes
      ansible_become_method: sudo
      ansible_become_password: "{{ lookup('env', 'BECOME_PASSWORD') }}"
