---
- name: Include installation tasks
  ansible.builtin.include_tasks: install.yml

- name: Include oauth2-proxy tasks
  ansible.builtin.include_tasks: oauth2_proxy.yml

- name: Include nginx configuration tasks
  ansible.builtin.include_tasks: configure.yml

- name: Include SSL/TLS tasks
  ansible.builtin.include_tasks: ssl.yml
